### ISSUE TITLE
Vehicle key

### ISSUE THREAD

**Issue by ivegotthis** [EliasAN1/lu-hunting#1]
Hi, I have a suggestion or a issue depending on how you look at it. When you rent a vehicle from the hunter, it's locked and you have no keys. As alot of servers have qb-vehiclekeys or variants of it, could you make it so we're given a key for the vehicle?
Thanks.

**Comment by EliasAN1** [comment]
Hello, sorry for the late reply, I just saw it.
For servers that uses qb-vehiclekeys it should work just fine, I just tested it and its working using qb-vehiclekeys but for other scripts you will have to modify it to work with your script as I don't have much experience in other keys scripts.

Can you tell me your server name to go test it ?
